// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwjwpfuaygfojwrrstly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3andwZnVheWdmb2p3cnJzdGx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMDg2OTQsImV4cCI6MjA2NjU4NDY5NH0.xG-plwEbUroKI41iJlMcIyYzlPtuHZCkUVfuSjgd6Iw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);